### ISSUE TITLE
Tests failing with Go 1.7+

### ISSUE THREAD

**Issue by trustmaster** [trustmaster/goflow#34]
```
$ go test
panic: send on closed channel

goroutine 1033 [running]:
github.com/trustmaster/goflow.(*counter).Loop(0xc4201a1680)
	/Users/trustmaster/go/src/github.com/trustmaster/goflow/component_test.go:426 +0x1c0
github.com/trustmaster/goflow.RunProc.func7(0x101, 0xc420075a10, 0xc420314250, 0x250c1f0, 0xc4201a1680, 0xc4200f90e0, 0xc4200759e0, 0xc4200f9100, 0x0, 0xc4200759b0)
	/Users/trustmaster/go/src/github.com/trustmaster/goflow/component.go:283 +0x2d8
created by github.com/trustmaster/goflow.RunProc
	/Users/trustmaster/go/src/github.com/trustmaster/goflow/component.go:309 +0x1408
exit status 2
FAIL	github.com/trustmaster/goflow	0.040s
```

**Comment by trustmaster** [comment]
Was getting this due to my outdated git clone, so non-issue
